site_name: JSEPA
repo_url: https://github.com/OxNinja/jsepa
repo_name: OxNinja/jsepa

theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    logo: fontawesome/brands/js-square
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
